services:
  app:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/mydb"
      REDIS_URL: "redis://redis:6379"
      SERVER_ADDR: "0.0.0.0:3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - app-network
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:

networks:
  app-network:
    driver: bridge